name: Build Docker Image

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
            - '8.1'
            - '8.2'
            - '8.3'
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build base and push
        run: ./build.sh ${{ matrix.php }}

      - name: Push
        run: |
            docker push ghcr.io/${{ github.repository }}:${{ matrix.php }}
            docker push ghcr.io/${{ github.repository }}:${{ matrix.php }}-fpm
            docker push ghcr.io/${{ github.repository }}:${{ matrix.php }}-caddy
