name: Build Docker Image

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
            - '8.1'
            - '8.2'
            - '8.3'
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (fpm)
        uses: docker/build-push-action@v5
        with:
            context: fpm
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ghcr.io/${{ github.repository }}:${{ matrix.php }}-fpm

      - name: Build and push (caddy)
        uses: docker/build-push-action@v5
        with:
            context: caddy
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
                ghcr.io/${{ github.repository }}:${{ matrix.php }}
                ghcr.io/${{ github.repository }}:${{ matrix.php }}-caddy
